// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkajtkvpphypvsjipttw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYWp0a3ZwcGh5cHZzamlwdHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTYxODUsImV4cCI6MjA2MDgzMjE4NX0.EbrxO-yI7Y9qw0Y9cT9XC-gOdrIT9pxfBdeSxZIRukY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);